#!/usr/bin/env python
# #support	:Trolard Vincent
# copyright	:Vincannes

ASSETS = "Total Assets"
BPA = "trailingEps"
BPA_HST = "DilutedEPS"
BOOK_VALUE = "bookValue"
CAPITALISATION = "marketCap"
CASHFLOW = "freeCashflow"
CASHFLOW_HST = "Free Cash Flow"
CASHFLOW_OPERATIONEL_HST = "Operating Cash Flow"
CASHFLOW_ACTION = "totalCashPerShare"
COMPAGNY_NAME = "shortName"
COST_REVENUE = "CostOfRevenue"
CLOSE_HST = "Close"
oldCLOSE_HST = "Adj Close"
CURR_RATIO = "currentRatio"
DEBT = "totalDebt"
DEBT_HST = "Total Debt"
DEBT_LONG_TERM_HIST = "Long Term Debt"
DIVIDENDE = "trailingAnnualDividendRate"
DIVIDENDE_HST = "dividendRate"
EBITDA = "ebitda"
EBITDA_HST = "EBITDA"
INDUSTRY = "industryKey"
LAST_PRICE = "currentPrice"
NET_INCOME = "netIncomeToCommon"
NET_INCOME_HST = "NetIncome"
ROA = "returnOnAssets"
ROE = "returnOnEquity"
REVENUE = "totalRevenue"
REVENUE_HST = "TotalRevenue"
REVENUE_SHARE = "revenuePerShare"
SHARES = "sharesOutstanding"
SHARES_HST = "BasicAverageShares"
SYMBOL = "symbol"
TOTAL_PASSIF_HIST = "Total Liabilities Net Minority Interest"
TOTAL_PASSIF_SHORT_TERM_HIST = "Current Liabilities"
